

#ifndef OWC_NETWORK_ERROR_CODES_H
#define OWC_NETWORK_ERROR_CODES_H

#define OWC_NETWORK_ERROR_CONNECTION_REFUSED 0x11
#define OWC_NETWORK_ERROR_WRITE_ERROR 0x12
#define OWC_NETWORK_ERROR_READ_ERROR 0x13

#endif
